version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: exchange_store
    healthcheck:
      test: "mysql --user=root --password=123456 --execute \"SHOW DATABASES;\""
      timeout: 5s
      retries: 3
    ports:
      - "3307:3306"
  app:
    image: ecol_task
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8888:8080"